version: '3.8'

services:
  # MySQL数据库服务
  mysql:
    image: mysql:8.0
    container_name: hello-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root123}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-hello_db}
      MYSQL_USER: ${MYSQL_USER:-hello_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-hello123}
    ports:
      - "127.0.0.1:${MYSQL_PORT:-3306}:3306"  # 只允许本地访问MySQL
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - hello-network
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Spring Boot应用服务
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: hello-app
    restart: unless-stopped
    environment:
      # 应用配置
      APP_NAME: ${APP_NAME:-hello}
      SERVER_PORT: ${SERVER_PORT:-8080}

      # 数据库配置
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: ${MYSQL_DATABASE:-hello_db}
      DB_USERNAME: ${MYSQL_USER:-hello_user}
      DB_PASSWORD: ${MYSQL_PASSWORD:-hello123}

      # JPA配置
      JPA_DDL_AUTO: ${JPA_DDL_AUTO:-update}
      JPA_SHOW_SQL: ${JPA_SHOW_SQL:-false}
      JPA_FORMAT_SQL: ${JPA_FORMAT_SQL:-false}

      # JVM配置
      JAVA_OPTS: ${JAVA_OPTS:--Xmx512m -Xms256m}

      # 服务器配置
      SERVER_HOST: ${SERVER_HOST:-152.53.168.97}
      SERVER_ADDRESS: 0.0.0.0

      # 日志配置
      LOGGING_LEVEL: ${LOGGING_LEVEL:-INFO}
      LOGGING_WEB_LEVEL: ${LOGGING_WEB_LEVEL:-INFO}
      LOGGING_SQL_LEVEL: ${LOGGING_SQL_LEVEL:-WARN}
    ports:
      - "0.0.0.0:${APP_PORT:-8080}:8080"  # 允许所有IP访问应用
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - hello-network
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mysql_data:
    driver: local

networks:
  hello-network:
    driver: bridge
